# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Rifky Ekayama | Professional Programmer and Web Developer
tagline: > 
  Web Developer and Freelancer
resume_hard_copy: #
photo_profile: profile_img_baru.jpg

#Identity
name: Rifky Ekayama
birthdate: February 09, 1994
email: rifky.ekayama@gmail.com
phone: +62878-2193-6074
whatsapp: +62878-2193-6074
address: Jl. KPAD Sriwijaya 1 No. 26 RT.03/08 Kota Cimahi,40524
cv: Rifky-Ekayama.pdf

description: > # this means to ignore newlines until "baseurl:"
 I am passionate about developing web based application using framework such as Laravel Framework , etc. I also interested on networking and server administration. I always follow the development of technology, especially web technology, because I love it.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://rifkyekayama.github.io" # the base hostname & protocol for your site

#Social Link
facebook_link: https://web.facebook.com/rifky.ekayama
twitter_link: https://twitter.com/RifkyEkayama
linkedin_link: http://id.linkedin.com/in/rifkyekayama
googleplus_link: https://plus.google.com/103502971739568065625
instagram_link: https://www.instagram.com/rifkyekayama/
skype_username: rifky.ekayama
github_link: https://github.com/rifkyekayama
gitlab_link: https://gitlab.com/u/rifky.ekayama
bitbucket_link: https://bitbucket.org/rifkyekayama/

# Build settings
markdown: kramdown
