# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Rifky Ekayama | Professional Programmer and Web Developer
tagline: 

#Identity
name: Rifky Ekayama
email: rifky.ekayama@gmail.com
phone: +62878-2193-6074
address: Jl. Sriwijaya 1 No. 26 RT.03/08 KPAD Sriwijaya, 40524

description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://rifkyekayama.github.io" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
